services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    container_name: todo-app-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data: